#! /usr/bin/env node

/**
 * Entry point for the bitstats program.
 */

const pkg = require('./package.json');
const program = require('commander');

program
  .description(pkg.description)
  .version(pkg.version)
  .command('pr', 'Pull request export and indexing')
  .command('repo', 'Repository listing and indexing')
  .command('setup', 'Setup credentials & authentication with Bitbucket')
  .parse(process.argv);
